version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore .\src\Sitecore.Js.Presentation.sln
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: Environment
  name: NuGet.org
  on:
    branch: master